### ISSUE TITLE
deprecated function in PHP 7.4 version

### ISSUE THREAD

**Issue by Ferikl** [iignatov/LightOpenID#20]
Hi, I am trying to use this lib to work with Steam and have error:

```
ERROR: Function get_magic_quotes_gpc() is deprecated {"exception":"[object] (ErrorException(code: 0): Function get_magic_quotes_gpc() is deprecated at /var/www/app/vendor/iignatov/lightopenid/openid.php:891)
[stacktrace]
#0 /var/www/app/vendor/iignatov/lightopenid/openid.php(891): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8192, 'Function get_ma...', '/var/www/app/ve...', 891, Array)
#1 /var/www/app/vendor/socialiteproviders/steam/Provider.php(58): LightOpenID->validate()
```

I am using PHP 7.4.2

**Comment by vaschepoh** [comment]
The same trouble.

**Comment by volkv** [comment]
Yep, Laravel Socialite Steam login not working with PHP 7.4

**Comment by david-nagel** [comment]
get_magic_quotes_gpc returns always false since PHP 5.4: 
https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

If you're using a more recent version it should be safe to replace 
`function_exists('get_magic_quotes_gpc') && get_magic_quotes_gpc() ? stripslashes($value) : $value;`
with
`$value`

**Comment by volkv** [comment]
@iignatov help us please

**Comment by benjivm** [comment]
This package is [abandoned](https://github.com/iignatov/LightOpenID/issues/9#issuecomment-186659836), the Socialite team needs to replace it.
